http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /bento
  debug_endpoints: true

input:
  label: ""
  broker:
    inputs:
      - mongodb:
          url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
          database: "CustomersDB"
          collection: "outbox"
          operation: find
          json_marshal_mode: canonical
          query: |
            root.status = "pending"
          auto_replay_nacks: true
          batch_size: 1000
          sort: {"created_at": 1}

pipeline:
  processors:
    - mapping: |
        meta = {
          "original": this,
          "myid": this._id.get("$oid"),
          "event_type": this.event_type
        }
        
        if meta.event_type == "CustomerDeleted" {
          root = this.payload
          root.deleted = true
          root.updated_at = now()
        } else {
          root = this.payload
          root.updated_at = now()
        }

    - mongodb:
        url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
        database: "OrderingDB"
        collection: "projection_customers"
        operation: update-one
        filter_map: |
          root = {"_id": this._id}
        document_map: |
          root = {"$set": this}
        upsert: true
        write_concern:
          w: 1
          j: true
          w_timeout: "10s"

    - mapping: |
        root = metadata("original")
        root.myid = metadata("myid")
        root.status = "processed"
        root.updated_at = now()

    - log:
        message: "processed: {{meta('original')}}"
        fields_mapping: |
          root = this
        level: "INFO"

    - mongodb:
        url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
        database: "CustomersDB"
        collection: "outbox"
        operation: update-one
        filter_map: |
          root = {"_id": {"$oid": this.myid}}
        document_map: |
          root = {"$set": {"status": this.status, "updated_at": this.updated_at}}
        write_concern:
          w: 1
          j: true
          w_timeout: "10s"
    
output:
  label: ""
  stdout:
    codec: lines
