http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /bento
  debug_endpoints: true

input:
  label: ""
  broker:
    inputs:
      - generate:
          interval: 60s
          mapping: |
            root = {"timestamp": timestamp_unix()}
      
      - mongodb:
          url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
          database: "CustomersDB"
          collection: "outbox"
          operation: find
          json_marshal_mode: canonical
          query: |
            root.Status = "pending"
          auto_replay_nacks: true
          batch_size: 100
          sort: {"created_at": 1}

pipeline:
  threads: 1
  processors:
    - mapping: |
        root = this
        meta = {"success": "yes"}

    - mapping: |
        let customer = this
        root = {
          "_id": customer._id,
          "name": customer.name,
          "email": customer.email,
          "created_at": customer.created_at,
          "updated_at": timestamp_unix()
        }

    - mongodb:
        url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
        database: "OrderingDB"
        collection: "customers_projection"
        operation: update-one
        filter_map: |
          root._id = this._id
        document_map: |
          root = {"$set": this}
        upsert: true
        write_concern:
          w: "majority"
          j: true
          w_timeout: "10s"
    
    - mapping: |
        let status = if meta("success") == "yes" { "processed" } else { "failed" }
        let update = {
          "Status": status,
          "UpdatedAt": timestamp_unix()
        }
        if meta("success") != "yes" {
          update.Error = error()
        }
        let result = {"$set": update}
        if meta("success") != "yes" {
          result = result.merge({"$inc": {"RetryCount": 1}})
        }
        root = result
        meta = {"update": result}

    - mongodb:
        url: "mongodb://localhost:27017/?replicaSet=rs0&directConnection=true"
        database: "CustomersDB"
        collection: "outbox"
        operation: update-one
        filter_map: |
          root._id = this._id
        document_map: |
          root = meta("update")

output:
  label: ""
  stdout:
    codec: lines
